# Generated by Django 2.1.2 on 2018-10-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_place', models.CharField(max_length=100)),
                ('unloading_place', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=24)),
                ('truck_type', models.CharField(choices=[('FRIGO', 'Frigo'), ('TAUT', 'Tautliner')], default='TAUT', max_length=10)),
            ],
        ),
    ]
