# Generated by Django 2.1.2 on 2018-10-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='info',
            field=models.CharField(default='<not required>', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='truck_type',
            field=models.CharField(choices=[('TAUT', 'Tautliner'), ('FRIGO', 'Frigo'), ('TANK', 'Tank')], default='TAUT', max_length=10),
        ),
    ]
