# Generated by Django 2.1.2 on 2018-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_auto_20181013_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='truck_type',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='info',
            field=models.TextField(blank=True, default='<not required>', max_length=100),
        ),
    ]
