# Generated by Django 2.1.2 on 2018-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_auto_20181014_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='info',
            field=models.TextField(default='<not required>', max_length=100, null=True),
        ),
    ]
