# Generated by Django 2.1.2 on 2018-10-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0006_auto_20181019_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='info',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
