# Generated by Django 2.1.2 on 2018-10-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0008_auto_20181019_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.SmallIntegerField(default=24),
        ),
    ]
