# Generated by Django 2.1.2 on 2018-10-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0009_auto_20181019_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.SlugField(default=24, max_length=2),
        ),
    ]
