# Generated by Django 2.1.2 on 2018-10-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0010_auto_20181019_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='loading_place',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='unloading_place',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.IntegerField(default=24),
        ),
    ]
