# Generated by Django 2.1.2 on 2018-10-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0011_auto_20181020_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='truck_type',
            field=models.CharField(choices=[('TR', 'Tautliner'), ('FO', 'Frigo'), ('TK', 'Tank')], default='TR', max_length=3),
        ),
    ]
