# Generated by Django 2.1.2 on 2018-10-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0012_shipment_truck_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='truck_type',
            field=models.CharField(max_length=3),
        ),
    ]
