# Generated by Django 2.1.2 on 2018-10-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0013_auto_20181021_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='currency',
            field=models.CharField(choices=[('EUR', 'euro'), ('SEK', 'sek'), ('PLN', 'pln')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='truck_type',
            field=models.CharField(choices=[('TR', 'Tautliner'), ('FO', 'Frigo'), ('TK', 'Tank')], default='TR', max_length=3),
        ),
    ]
