# Generated by Django 2.1.2 on 2018-10-22 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0015_auto_20181021_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
