# Generated by Django 2.1.2 on 2018-10-23 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0017_auto_20181023_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='load_date_from',
        ),
        migrations.AddField(
            model_name='shipment',
            name='loadgin_date_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
