# Generated by Django 2.0.9 on 2018-10-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0019_auto_20181023_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='price',
            field=models.IntegerField(),
        ),
    ]
