# Generated by Django 2.1.2 on 2018-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0020_auto_20181025_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=10),
        ),
    ]
