# Generated by Django 2.0.9 on 2018-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0024_auto_20181108_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='closed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
