# Generated by Django 2.0.9 on 2018-11-08 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0025_auto_20181108_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
