# Generated by Django 2.1 on 2018-12-02 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0026_auto_20181108_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=70)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
