# Generated by Django 2.0.9 on 2018-12-06 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0035_auto_20181206_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.OneToOneField, to=settings.AUTH_USER_MODEL),
        ),
    ]
