# Generated by Django 2.0.9 on 2018-12-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0038_auto_20181206_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
    ]
